//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Countdown.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_COUNTDOWN_DIALOG            102
#define IDR_MAINFRAME                   128
#define IDI_ICON_TIME                   130
#define IDI_ICON_AFTER                  131
#define IDI_ICON_MSG                    133
#define IDI_ICON_MSG_AFTER              134
#define IDI_ICON_TIME_AFTER             135
#define IDD_DIALOG_RECORDTIMES          136
#define IDD_DIALOG_MAINTAIN             137
#define IDR_MAIN_MENU                   138
#define IDD_DIALOG_RECORDING_PROPERTIES 142
#define IDC_BUTTON_RECORD               1000
#define IDC_COMBO_RECORD_MSG            1001
#define IDC_LIST_MESSAGES               1002
#define IDC_BUTTON_ADD                  1003
#define IDC_COMBO_CONTENT_MSG           1004
#define IDC_RADIO_CONTENT_MSG           1005
#define IDC_RADIO_CONTENT_TIME          1006
#define ID_CANCEL_BTN                   1007
#define IDC_COMBO_FREQ_MSG              1008
#define IDC_RADIO_CONTENT_STARTERS      1009
#define IDC_COMBO_CONTENT_FORMAT        1011
#define IDC_RADIO_TIMING_FINISH         1013
#define IDC_RADIO_TIMING_START          1014
#define IDC_BUTTON_COPY                 1015
#define IDC_BUTTON_DELETE               1016
#define IDC_BUTTON_EXIT                 1017
#define IDC_BUTTON_MODIFY               1017
#define IDC_BUTTON_SAVE                 1018
#define IDC_BUTTON_ADDMODE              1018
#define IDC_BUTTON_CREATE               1019
#define IDC_BUTTON_TEST                 1020
#define IDC_BUTTON_PLAYREC              1020
#define IDC_RADIO_FREQ_EVERY            1021
#define IDC_RADIO_FREQ_AFTER_MSG        1022
#define IDC_EDIT_TIMING_FINISH_HH       1023
#define IDC_EDIT_TIMING_FINISH_MM       1024
#define IDC_EDIT_TIMING_FINISH_SS       1025
#define IDC_EDIT_FREQ_HH                1026
#define IDC_BUTTON_ADDAFTER             1026
#define IDC_EDIT_FREQ_MM                1027
#define IDC_EDIT_FREQ_SS                1028
#define IDC_EDIT_TIMING_START_HH        1029
#define IDC_EDIT_OFFSET_HH              1029
#define IDC_EDIT_TIMING_START_MM        1030
#define IDC_EDIT_OFFSET_MM              1030
#define IDC_EDIT_TIMING_START_SS        1031
#define IDC_EDIT_OFFSET_SS              1031
#define IDC_COMBO_TIMING_FINISH         1032
#define IDC_COMBO_TIMING_START          1033
#define IDC_EDIT_TIMING_MSG_HH          1034
#define IDC_EDIT_TIMING_MSG_MM          1035
#define IDC_EDIT_TIMING_MSG_SS          1036
#define IDC_EDIT_FIRST_HH               1038
#define IDC_EDIT_FIRST_MM               1039
#define IDC_EDIT_FIRST_SS               1040
#define IDC_EDIT_LAST_HH                1041
#define IDC_EDIT_LAST_MM                1042
#define IDC_EDIT_LAST_SS                1043
#define IDC_EDIT_NEXT_PLUS_MM           1043
#define IDC_EDIT_TIMING_MSG_TT          1044
#define IDC_EDIT_STARTERS_PLUS_MM       1044
#define IDC_STATIC_MSG_NAME             1045
#define IDC_EDIT_TIMING_FINISH_TT       1046
#define IDC_EDIT_TIMING_START_TT        1047
#define IDC_DYN_LED                     1048
#define IDC_EDIT_FILENAME               1049
#define IDC_BUTTON_BROWSE               1050
#define IDC_BUTTON_AMPLIFY              1051
#define IDC_EDIT_AMPLIFY                1052
#define IDC_EDIT_STARTLISTFILE          1052
#define IDC_SPIN_AMPLIFY                1053
#define IDC_BUTTON_BROWSE2              1053
#define IDC_BUTTON_BROWSE_STARTLIST     1053
#define IDC_BUTTON_PLAY                 1054
#define IDC_BUTTON_DAMPEN               1055
#define IDC_CHECK_SEQUENTIAL            1056
#define IDC_SPIN_NUMBER                 1057
#define IDC_STATIC_NUMBER               1058
#define IDC_COMBO_RELATIVE              1060
#define IDC_STATIC_PUNC1                1061
#define IDC_STATIC_PUNC2                1062
#define IDC_STATIC_PUNC3                1063
#define IDC_STATIC_PUNC4                1064
#define IDC_STATIC_PUNC5                1065
#define IDC_STATIC_PUNC6                1066
#define IDC_STATIC_PUNC7                1067
#define IDC_LIST_RECS                   1068
#define IDC_STATIC_PUNC8                1068
#define ID_BTN_DELETE                   1069
#define IDC_STATIC_PUNC9                1069
#define IDC_RADIO_MESSAGES              1070
#define IDC_RADIO_TIMES                 1071
#define IDC_STATIC_GNU                  1073
#define IDC_STATIC_FREQ_SECONDS         1074
#define IDC_COMBO_VOICE                 1075
#define ID_MENU_CREATE                  32771
#define ID_MENU_EXIT                    32772
#define ID_MENU_MAINTENANCE             32773
#define ID_MENU_CLOCK                   32774
#define ID_MENU_CONTENTS                32775
#define ID_MENU_HELP_INDEX              32776
#define ID_MENU_ABOUT                   32777
#define ID_MENU_HELP_CONTENTS           32778
#define ID_MENU_OFFSET                  32779
#define ID_MENU_EXPORT                  32780
#define ID_MENU_IMPORT                  32781
#define ID_OPTIONS_RECORDING            32782
#define ID_MENU_RECORDING               32783

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32784
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
